# ruff settings
# https://docs.astral.sh/ruff/settings/

# https://docs.astral.sh/ruff/settings/#line-length
line-length = 120
# https://docs.astral.sh/ruff/settings/#show-fixes
show-fixes = true
# enable preview mode
# https://docs.astral.sh/ruff/preview/
preview = true
target-version = 'py312'

# https://docs.astral.sh/ruff/settings/#lint
[lint]
# https://docs.astral.sh/ruff/settings/#lint_select
# Rules: https://docs.astral.sh/ruff/rules/
select = [
    # pycodestyle
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",
    "W",
    # Pyflakes
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F",
    # mccabe
    # https://docs.astral.sh/ruff/rules/#mccabe-c90
    "C90",
    # isort
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I",
    # pep8-naming
    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",
    # pyupgrade
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",
    # flake8-bandit
    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "S",
    # flake8-blind-except
    # https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    "BLE",
    # flake8-boolean-trap
    # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
    "FBT",
    # flake8-bugbear
    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "B",
    # flake8-builtins
    # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "A",
    # flake8-comprehensions
    # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "C4",
    # flake8-datetimez
    # https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
    "DTZ",
    # flake8-errmsg (EM)
    # https://docs.astral.sh/ruff/rules/#flake8-errmsg-em
    # "EM",
    # flake8-executable
    # https://docs.astral.sh/ruff/rules/#flake8-executable-exe
    "EXE",
    # flake8-implicit-str-concat
    # https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
    "ISC",
    # flake8-import-conventions
    # https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
    "ICN",
    # flake8-no-pep420
    # https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
    # "INP",
    # flake8-logging
    # https://docs.astral.sh/ruff/rules/#flake8-logging-log
    "LOG",
    # TODO: Use G (logging format)?
    # flake8-quotes
    # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "Q",
    # flake8-return
    # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RET",
    # flake8-self
    # https://docs.astral.sh/ruff/rules/#flake8-self-slf
    "SLF",
    # flake8-simplify
    # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "SIM",
    # flake8-tidy-imports
    # https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    "TID",
    # flake8-type-checking
    # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
    "TC",
    # flake8-unused-arguments (ARG)
    # https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "ARG",
    # flake8-use-pathlib
    # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "PTH",
    # eradicate
    # https://docs.astral.sh/ruff/rules/#eradicate-era
    "ERA",
    # pylint
    # https://docs.astral.sh/ruff/rules/#pylint-pl
    "PL",
    # tryceratops
    # https://docs.astral.sh/ruff/rules/#tryceratops-try
    "TRY",
    # perflint
    # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PERF",
    # refurb
    # https://docs.astral.sh/ruff/rules/#refurb-furb
    "FURB",
    # ruff
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF",
]

# https://docs.astral.sh/ruff/settings/#lintflake8-quotes
[lint.flake8-quotes]
inline-quotes = "single"

# https://docs.astral.sh/ruff/settings/#format
[format]
quote-style = "single"
indent-style = "space"
